# Retail Crime in OBIS Database

Data Source: April 2022 Dataset from Florida's OBIS Database http://www.dc.state.fl.us/pub/obis_request.html

-----

In [1]:
#Import libraries
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
from plotnine import *

/Users/sm/.pyenv/versions/3.10.0/lib/python3.10/site-packages/pandas/compat/__init__.py:124: UserWarning: Could not import the lzma module. Your installed Python is incomplete. Attempting to use lzma compression will result in a RuntimeError.
  warnings.warn(msg)

In [2]:
%load_ext rpy2.ipython
%load_ext autoreload
%autoreload 2

%matplotlib inline  
from matplotlib import rcParams
rcParams['figure.figsize'] = (16, 100)

import warnings
from rpy2.rinterface import RRuntimeWarning
warnings.filterwarnings("ignore") # Ignore all warnings
# warnings.filterwarnings("ignore", category=RRuntimeWarning) # Show some warnings

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from IPython.display import display, HTML

In [ ]:
%%R

# My commonly used R imports

require('ggplot2')
require('readr')
require('extrafont')
require('dplyr')
require('reshape2')
# require('theme538')

In [4]:
pd.set_option("display.max_columns", None)

-----

# Importing April 2022 from OBIS Database

Inmate (Active): Root, Alias, Offenses_CPS, Offenses_PRPR, Detainers, Incarhist <br>
Inmate (Release): Root, Alias, Offenses_CPS, Offenses_PRPR, Detainers, Incarhist. <br>
Offender: Root, Offenses_CCS, Residence

In [5]:
# FDOC April 2022
df_fdoc = pd.read_excel("../data/source/FL-OBIS/FDOC_Apr_2022.XLSX")

In [6]:
df_fdoc.sample(5)

                      memname                      name  type  length  varnum
108     OFFENDER_OFFENSES_CCS  adjudicationcharge_descr  char      30       9
114  OFFENDER_RESIDENCE_FINAL                   ZipCode  char       9       6
106     OFFENDER_OFFENSES_CCS             ProbationTerm  char       7       7
6     INMATE_ACTIVE_DETAINERS                 Authority  char      30       2
32         INMATE_ACTIVE_ROOT                  LastName  char      30       2

### Current Community Supervision Offenders Files

Offender_root: Basic offender information on current community supervision offenders <br>
Offender_aliases: Aliases for offenders <br>
Offender_offenses_CCS: Current community supervision offenses for offenders <br>
Offender_residence: Most recent address (excluding confidential addresses) for offenders

In [7]:
# Offender_root: Basic offender information on current community supervision offenders
df_offender_root = pd.read_excel("../data/source/FL-OBIS/offender/Offender_Apr_2022.XLSX")

In [8]:
df_offender_root.sample(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,SupervisionTerminationDate,ReceiptDate,supvtype_description,facility_description,supvstatus_description,race_descr
10758,427174,LOPEZ,PABLO,NaN,NaN,W,M,1969-11-25,1991-01-08 00:00:00,1989-01-09,PROBATION FELONY,MIAMI,ABSCONDER/FUGITIVE,WHITE
33190,C09023,HOLLISTER,ARTHUR,JAQUIN,NaN,W,M,1979-06-19,2025-01-18 00:00:00,2022-01-19,PROBATION FELONY,SARASOTA,ACTIVE,WHITE
64528,I54195,SALINAS AVILA,HECTOR,NaN,NaN,W,M,1976-10-13,2022-05-30 00:00:00,2017-05-31,PROBATION FELONY,FT. LAUDERDALE,ACTIVE SUSPENSE,WHITE
105995,R88504,KENNER,KEONDRA,NaN,NaN,B,F,1997-07-16,2021-11-04 00:00:00,2017-11-05,PROBATION FELONY,CLEARWATER,ACTIVE SUSPENSE,BLACK
27360,B05475,LAFRANCE,ARNOLD,NaN,NaN,B,M,1979-08-12,2029-01-26 00:00:00,2009-01-27,PROBATION FELONY,FT. LAUDERDALE,ACTIVE,BLACK

In [9]:
# Offender_residence: Most recent address (excluding confidential addresses) for offenders
df_offender_residence = pd.read_excel("../data/source/FL-OBIS/offender/Offender_Apr_2022_residence.XLSX")

In [10]:
df_offender_residence.sample(5)

,DCNumber,AddressLine1,AddressLine2,City,State,ZipCode,Country
118029,Y70102,2660 COREY AVE,NaN,W MELBOURNE,FL,32904.0,US
13566,659127,ABSCONDER - BROWARD,NaN,NaN,FL,NaN,US
95234,S81190,ABSCONDER - OKALOOSA,NaN,NaN,NaN,NaN,US
100269,U25204,5550 W HIGHWAY 318,NaN,REDDICK,FL,32686.0,US
99955,U17043,OTHER STATE PRISON,OS PRISON,NaN,NaN,NaN,US

In [11]:
# Offender_offenses_CCS: Current community supervision offenses for offenders 
df_offender_offenses_css = pd.read_excel("../data/source/FL-OBIS/offender/Offender_Apr_2022_offenses_css.XLSX")

In [12]:
df_offender_offenses_css.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,ProbationTerm,ParoleTerm,adjudicationcharge_descr
73107,B10119,1,2016-10-11,2017-04-17,LEON,1603084.0,50000,1024,ROBB. WPN-NOT DEADLY
283784,Q81098,1,2018-11-08,2021-04-26,SARASOTA,1903905.0,10600,0,BURGL UNOCC DWELLING
18457,258972,3,1990-12-24,1991-02-25,PINELLAS,9002052.0,20000,0,BURGUNOCCSTRUC/CV OR ATT.
248704,N41132,5,2020-07-29,2021-06-23,BROWARD,2006285.0,2400,0,COCAINE - POSSESSION
155427,H40766,7,2009-10-26,2012-11-30,POLK,1005625.0,240000,0,GRAND THEFT O/$100K

In [13]:
# Offender_aliases: Aliases for offenders
df_offender_alias = pd.read_excel("../data/source/FL-OBIS/offender/Offender_Apr_2022_alias.XLSX")

In [14]:
df_offender_alias.sample(5)

       DCNumber        LastName  FirstName MiddleName NameSuffix
405747   V90381             YEH      KAREN        NaN        NaN
410079   W34164          HOLMES     WILLIE        LEE        NaN
330776   R14586         HOLLAND      COREY     ERNEST        NaN
297206   N80904          MORTEN  BRIONSHAE        NaN        NaN
311905   P81325  GEORGIADISVERA      HARIS        NaN        NaN

In [15]:
df_offender = pd.merge(df_offender_root, df_offender_residence, on='DCNumber', how='outer')
df_offender.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,SupervisionTerminationDate,ReceiptDate,supvtype_description,facility_description,supvstatus_description,race_descr,AddressLine1,AddressLine2,City,State,ZipCode,Country
38044,D35385,DE LA OSA,JOEL,NaN,NaN,W,M,1969-01-09,2029-09-28 00:00:00,2017-09-29,PROBATION FELONY,MIAMI,ACTIVE,WHITE,10775 NW 50TH ST,APT# 105,DORAL,FL,33178.0,US
42810,E49653,ASHBY,BRANDON,MICHAEL,NaN,W,M,1991-11-07,2022-12-07 00:00:00,2020-12-08,PROBATION FELONY,SANFORD,ACTIVE,WHITE,5161 PALMETTO AVE,NaN,COCOA,FL,32926.0,US

In [16]:
df_offender.shape

(138849, 20)

In [17]:
df_offender = pd.merge(df_offender, df_offender_offenses_css, on='DCNumber', how='outer')
df_offender.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,SupervisionTerminationDate,ReceiptDate,supvtype_description,facility_description,supvstatus_description,race_descr,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,ProbationTerm,ParoleTerm,adjudicationcharge_descr
96971,C71392,CUMMINGS,ANTONIO,NaN,NaN,B,M,2000-09-05,2023-07-23 00:00:00,2022-01-24,PROBATION FELONY,CLEARWATER,ACTIVE,BLACK,1443 40TH ST S,NaN,ST PETERSBURG,FL,33711.0,US,1.0,2021-06-11,2022-01-24,PINELLAS,2105520.0,10600.0,0.0,CARRYING CONCEALED FIREARM
193132,K00724,GARCIA,ALEXIS,NaN,NaN,W,M,1975-12-15,2025-12-04 00:00:00,2018-12-05,PROBATION FELONY,MIAMI,ACTIVE SUSPENSE,WHITE,1321 NW 13TH ST,MIAMI-DADE COUNTY JAIL,MIAMI,FL,33125.0,US,5.0,2018-07-27,2018-12-05,MIAMI-DADE,1816110.0,50000.0,0.0,"GRAND THEFT,300 L/5,000"

In [18]:
df_offender.shape

(381915, 28)

### Active Inmate Files

Inmate_active_root:  Basic inmate information on active inmates <br>
Inmate_active_aliases: Aliases for these active inmates <br>
Inmate_active_offenses_CPS: Current prison offenses for these active inmates <br>
Inmate_active_offenses_prpr: Prior prison offenses for these active inmates <br>
Inmate_active_detainers: Detainers for these active inmates <br>
Inmate_active_incarhist: Incarceration history for these active inmates

In [19]:
# Inmate_active_root: Basic inmate information on active inmates
df_active_root = pd.read_excel("../data/processed/Inmate_Active_Apr_2022_PROCESSED_FILTERED_Inmate_Active_Root.xlsx")

In [20]:
df_active_root.sample(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description
56793,P24529,COOK,ROY,C,JR,B,M,1984-10-15,2033-06-10 00:00:00,2019-08-08,valid release date,BLACK,MEDIUM,UNION WORK CAMP
13691,354952,STEVERSON,BOBBY,L,NaN,W,M,1964-06-26,NaN,1995-08-15,life sentence,WHITE,CLOSE,HARDEE C.I.
72678,V32738,ROREM,AUSTIN,D,NaN,W,M,1980-09-21,2022-04-01 00:00:00,2021-07-13,valid release date,WHITE,MEDIUM,BLACKWATER C.F.
2568,083510,CROSS,CRAIG,NaN,NaN,B,M,1966-06-03,NaN,1984-06-22,life sentence,BLACK,CLOSE,BLACKWATER C.F.
63884,S12972,BOATMAN,SHANNON,N,NaN,W,F,1980-03-02,2022-04-01 00:00:00,2018-01-17,valid release date,WHITE,MINIMUM,LOWELL C.I.

In [21]:
# Inmate_active_offenses_prpr: Prior prison offenses for these active inmates
df_active_offenses_prpr = pd.read_excel("../data/source/FL-OBIS/active/Inmate_Active_Apr_2022_offenses_prpr.xlsx")

In [22]:
df_active_offenses_prpr.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
158458,I04380,4,2006-10-03,2007-11-26,SUWANNEE,700305.0,10100,GRAND THEFT FIREARM
197009,Q14909,1,2003-10-16,2009-01-05,BAY,303386.0,10800,ROBB. NO GUN/DDLY.WPN
65074,367613,9,1993-02-06,1995-06-27,POLK,9300472.0,30600,CONSTRUCTIVE POSSESSION
66769,384998,13,1980-08-20,1983-10-25,MIAMI-DADE,8301751.0,90,FRAUD-CHECK
217744,T35739,1,2003-03-31,2003-08-21,HILLSBOROUGH,305153.0,50000,FEL/DELI W/GUN/CONC WPN/AMMO

In [23]:
# Inmate_active_offenses_CPS: Current prison offenses for these active inmates
df_active_offenses_cps = pd.read_excel("../data/processed/Inmate_Active_Apr_2022_PROCESSED_FILTERED_Inmate_Active_Offenses_CPS.xlsx")

In [24]:
df_active_offenses_cps.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
237905,P64016,6,2017-08-04,2018-03-15,CALHOUN,1704517.0,50000,BURGUNOCCSTRUC/CV OR ATT.
62778,480639,13,1986-11-16,1998-11-13,HILLSBOROUGH,8617537.0,150000,ROBB. NO GUN/DDLY.WPN
7129,070857,2,2016-02-01,2020-06-11,ALACHUA,1704074.0,40200,THEFT SEMI DEPLOY. BY LEO
289361,U41968,1,2016-04-25,2018-01-17,VOLUSIA,1710521.0,70000,S/M/D OTH SCH I & II
56891,409410,7,2014-04-01,2015-07-27,LAKE,1500108.0,50000,AGG ASSLT-INTENT COMMIT FELONY

In [25]:
# Inmate_active_detainers: Detainers for these active inmates
df_active_detainers = pd.read_excel("../data/source/FL-OBIS/active/Inmate_Active_Apr_2022_detainers.xlsx")

In [26]:
df_active_detainers.sample(5)

,DCNumber,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
28485,C70295,HILLSBOROUGH CO SO,2019-03-05 00:00:00,D,2021-06-16,2,DETAIN
46248,T59432,13C:1415507,2019-03-11 00:00:00,N,NaT,2,NTFY/P&P
22697,M86738,BROWARD CO JAIL,2018-11-08 00:00:00,D,2019-01-09,1,DETAIN
21342,116202,NTFY.P&P PINELLAS CO,1989-04-13 00:00:00,D,1990-04-09,1,DETAIN
27208,S28561,SARASOTA CO JAIL,2015-05-20 00:00:00,D,2015-12-18,2,DETAIN

In [27]:
# Inmate_active_aliases: Aliases for these active inmates
df_active_alias = pd.read_excel("../data/processed/Inmate_Active_Apr_2022_PROCESSED_FILTERED_Inmate_Active_Aliases.xlsx")

In [28]:
df_active_alias.sample(5)

       DCNumber    LastName FirstName MiddleName NameSuffix
126240   750336  WHITTFIELD    REGINA        NaN        NaN
148231   986457       WELCH      ADAM        NaN        NaN
17716    095290       WEEKS     JERRY      WAYNE        NaN
148286   987062        VANN    MARCUS        NaN        NaN
329122   R65358      LIMETA      GANI        NaN        NaN

In [29]:
# Inmate_active_incarhist: Incarceration history for these active inmates
df_active_incarhist = pd.read_excel("../data/source/FL-OBIS/active/Inmate_Active_Apr_2022_incarhist.xlsx")

In [30]:
df_active_incarhist.sample(5)

       DCNumber ReceiptDate ReleaseDate
160607   V17191  2016-11-30  2017-08-20
128160   N10949  2012-08-02  2013-01-01
76395    966769  2014-10-09         NaT
146218   S29958  2016-08-24         NaT
130692   N91234  2021-12-09         NaT

In [31]:
df_active = pd.merge(df_active_root, df_active_offenses_cps, on='DCNumber', how='outer')
df_active.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
8933,079501,EVANS,EDWARD,M,NaN,W,M,1965-02-03,NaN,1994-09-01,life sentence,WHITE,CLOSE,EVERGLADES C.I.,14.0,1993-11-18,1994-11-14,HAMILTON,9300155.0,50000.0,"GRAND THEFT,$300 LESS &20,000"
136949,E29085,MCGOWEN,JOHN,A,NaN,W,M,1988-06-05,2027-04-16 00:00:00,2019-02-21,valid release date,WHITE,CLOSE,JACKSON C.I.,4.0,2018-02-28,2019-05-14,VOLUSIA,1810628.0,90409.0,CARJACK W/O FA/DEAD WEAP

In [32]:
df_active.shape

(336632, 21)

In [33]:
df_active = pd.merge(df_active, df_active_detainers, on='DCNumber', how='outer')
df_active.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
246060,H38158,RICHARDS,DOMINIC,A,NaN,B,M,1993-06-08,2030-07-11 00:00:00,2016-10-05,valid release date,BLACK,MEDIUM,WAKULLA ANNEX,4.0,2016-01-19,2016-08-22,POLK,1600634.0,150000.0,TRAFF COCAINE 28-U/200GR,NaN,NaN,NaN,NaT,NaN,NaN
134172,739864,GRAHAM,TORRANCE,L,NaN,B,M,1967-09-11,2024-08-18 00:00:00,2021-03-03,valid release date,BLACK,CLOSE,SUWANNEE C.I. ANNEX,19.0,2020-01-22,2021-02-17,SARASOTA,2006742.0,40000.0,SELL/ETC.COC/HER.1000FT SCH,SARASOTA CO SO,2021-03-23 00:00:00,D,NaT,4.0,DETAIN

In [34]:
df_active.shape

(474773, 27)

In [35]:
df_active_prpr = pd.merge(df_active, df_active_offenses_prpr, on='DCNumber', how='outer')
df_active_prpr.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence_x,OffenseDate_x,DateAdjudicated_x,County_x,CaseNumber_x,prisonterm_x,adjudicationcharge_descr_x,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr,Sequence_y,OffenseDate_y,DateAdjudicated_y,County_y,CaseNumber_y,prisonterm_y,adjudicationcharge_descr_y
581537,266431,DIRENZO,RICHARD,NaN,NaN,W,M,1974-12-27,2028-10-25 00:00:00,2015-08-18,valid release date,WHITE,CLOSE,CHARLOTTE C.I.,49.0,2013-11-05,2015-08-06,PINELLAS,1505142.0,200000.0,BURG/DWELL/OCCUP.CONVEY,PH 609-292-9093,2010-04-06 00:00:00,D,2010-10-01,10.0,DETAIN,16.0,2001-01-31,2001-06-29,PASCO,100797.0,20724.0,UTTER FORGED INSTRUMENT
1293955,792242,HAMILTON,CATHERINE,A,NaN,W,F,1965-07-03,2022-10-05 00:00:00,2020-01-10,valid release date,WHITE,MEDIUM,FL.WOMENS RECPN.CTR,47.0,2019-04-10,2019-12-06,CITRUS,1900420.0,40000.0,PETIT THEFT/3RD CONVICTION,HERNANDO CO SO,2006-01-11 00:00:00,D,2008-08-05,5.0,DETAIN,11.0,1988-04-01,1988-09-14,CITRUS,8800285.0,50000.0,FRAUD-CHECK

In [36]:
df_active_prpr.shape

(2857055, 34)

In [37]:
df_active.head(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
0,000069,PLATAS,DESIREE,A,NaN,W,F,1994-12-21,2026-06-26 00:00:00,2018-08-23,valid release date,WHITE,MINIMUM,LOWELL ANNEX,1.0,2015-11-21,2018-08-16,PALM BEACH,1610215.0,100000.0,ACCESSORY AFT.FACT-CAPITAL,NaN,NaN,NaN,NaT,NaN,NaN
1,000069,PLATAS,DESIREE,A,NaN,W,F,1994-12-21,2026-06-26 00:00:00,2018-08-23,valid release date,WHITE,MINIMUM,LOWELL ANNEX,2.0,2015-11-21,2018-08-16,PALM BEACH,1610215.0,100000.0,"ARSON,WILLFUL DAMA.STRUCT.",NaN,NaN,NaN,NaT,NaN,NaN
2,000084,ODOM,EDDIE,NaN,NaN,W,M,1940-01-01,NaN,1976-10-08,life sentence,WHITE,CLOSE,ZEPHYRHILLS C.I.,1.0,1976-01-27,1976-10-08,DUVAL,7600296.0,9999998.0,1ST DG MUR/PREMED. OR ATT.,NaN,NaN,NaN,NaT,NaN,NaN
3,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,5.0,2018-04-08,2020-12-21,JACKSON,1800606.0,40000.0,BURGL OCCUPIED DWELLING,NaN,NaN,NaN,NaT,NaN,NaN
4,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,6.0,2018-04-08,2020-12-21,JACKSON,1800606.0,40000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN

In [38]:
df_active_prpr.head(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence_x,OffenseDate_x,DateAdjudicated_x,County_x,CaseNumber_x,prisonterm_x,adjudicationcharge_descr_x,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr,Sequence_y,OffenseDate_y,DateAdjudicated_y,County_y,CaseNumber_y,prisonterm_y,adjudicationcharge_descr_y
0,000069,PLATAS,DESIREE,A,NaN,W,F,1994-12-21,2026-06-26 00:00:00,2018-08-23,valid release date,WHITE,MINIMUM,LOWELL ANNEX,1.0,2015-11-21,2018-08-16,PALM BEACH,1610215.0,100000.0,ACCESSORY AFT.FACT-CAPITAL,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN
1,000069,PLATAS,DESIREE,A,NaN,W,F,1994-12-21,2026-06-26 00:00:00,2018-08-23,valid release date,WHITE,MINIMUM,LOWELL ANNEX,2.0,2015-11-21,2018-08-16,PALM BEACH,1610215.0,100000.0,"ARSON,WILLFUL DAMA.STRUCT.",NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN
2,000084,ODOM,EDDIE,NaN,NaN,W,M,1940-01-01,NaN,1976-10-08,life sentence,WHITE,CLOSE,ZEPHYRHILLS C.I.,1.0,1976-01-27,1976-10-08,DUVAL,7600296.0,9999998.0,1ST DG MUR/PREMED. OR ATT.,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaT,NaT,NaN,NaN,NaN,NaN
3,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,5.0,2018-04-08,2020-12-21,JACKSON,1800606.0,40000.0,BURGL OCCUPIED DWELLING,NaN,NaN,NaN,NaT,NaN,NaN,1.0,2018-04-08,2019-05-14,JACKSON,1800606.0,1121.0,BURGL OCCUPIED DWELLING
4,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,5.0,2018-04-08,2020-12-21,JACKSON,1800606.0,40000.0,BURGL OCCUPIED DWELLING,NaN,NaN,NaN,NaT,NaN,NaN,2.0,2016-04-08,2019-05-14,JACKSON,1800606.0,1121.0,GRAND THEFT FIREARM

### Released Inmate Files

Inmate_release_root : Basic inmate information on inmates released since 10-1-1997 <br>
Inmate_release_aliases: Aliases for these released inmates  <br>
Inmate_release_offenses_CPS: Current prison offenses for these released inmates <br>
Inmate_release_offenses_prpr: Prior prison offenses for these released inmates <br>
Inmate_release_residence: Release plan address for these released inmates <br>
Inmate_release_detainers: Detainers for these released inmates <br>
Inmate_release_incarhist: Incarceration history for these released inmates <br>

In [39]:
# Inmate_release_root : Basic inmate information on inmates released since 10-1-1997
df_inmate_release_root = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_root.XLSX")

In [40]:
df_inmate_release_root.sample(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description
425262,Y10764,GUILLORI,AMELTON,NaN,NaN,B,M,1981-12-08,2010-04-14,valid release date,BLACK,MEDIUM,HENDRY C.I.
165933,A70044,BAKER,CLAYTON,B,NaN,W,M,1991-05-06,2020-09-16,valid release date,WHITE,COMMUNITY,MAYO C.I. ANNEX
245749,J30302,CARTWRIGHT,MALCOLM,A,NaN,B,M,1983-04-07,2016-02-28,valid release date,BLACK,MEDIUM,SANTA ROSA ANNEX
100050,503194,VIDAL,REINERIO,NaN,NaN,H,M,1959-07-09,2009-01-01,valid release date,HISPANIC,CLOSE,MADISON C.I.
90061,432848,WHITLEY,DARRYL,E,NaN,B,M,1963-08-12,2010-07-09,valid release date,BLACK,COMMUNITY,REALITY HOUSE

In [41]:
# Inmate_release_aliases: Aliases for these released inmates
df_inmate_release_alias1 = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_alias1.XLSX")

In [42]:
df_inmate_release_alias1.sample(5)

       DCNumber   LastName  FirstName MiddleName NameSuffix
945407   A50197   MATFIELD  ALEXANDER     MIHAIL        NaN
109034   109709      CROSS    PHILLIP        NaN        NaN
501970   442579      CADET      STEVE          J        NaN
535916   481487     PESHEK      IRENE     LOUISE        NaN
32821    052026  MCGREIGHT      DAVID  FREDERICK        NaN

In [43]:
# Inmate_release_aliases: Aliases for these released inmates
df_inmate_release_alias2 = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_alias2.XLSX")

In [44]:
df_inmate_release_alias2.sample(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description
402347,W20385,WELLS,DANIEL,M,NaN,B,M,1982-06-14,2014-09-15,valid release date,BLACK,MEDIUM,MOORE HAVEN C.F.
205461,E41128,RUSSELL,ALLEN,L,JR,W,M,1984-06-05,2019-11-01,valid release date,WHITE,MINIMUM,JACKSON C.I.
162534,992389,JONES,JIMMY,L,NaN,B,M,1977-08-17,2017-08-15,valid release date,BLACK,MINIMUM,HOLMES C.I.
377735,U19726,CRAW,NICOLE,L,NaN,W,F,1979-09-05,2012-08-25,valid release date,WHITE,CLOSE,LOWELL C.I.
314457,P59188,HERRING,DILLIAN,R,NaN,W,M,1996-12-04,2019-03-19,valid release date,WHITE,MEDIUM,COLUMBIA ANNEX

In [45]:
# Inmate_release_aliases: Aliases for these released inmates
df_inmate_release_alias3 = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_alias3.XLSX")

In [46]:
df_inmate_release_alias3.sample(5)

      DCNumber         LastName FirstName MiddleName NameSuffix
8571    W23480        CARMICHEL    EUGENE        NaN        NaN
69260   X54873       MCCLINTOCK   WILLIAM    STANLEY        NaN
81721   X72840  RODRIGUEZ-MCNAB      JAEL        NaN        NaN
55205   X37726           KNIGHT    JOHNNY        NaN        NaN
10905   W27245    SAULBERRY JR.     JAMES        NaN        NaN

In [47]:
# Inmate_release_offenses_CPS: Current prison offenses for these released inmates
df_inmate_release_offenses_cps1 = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_offenses_cps1.XLSX")

In [48]:
df_inmate_release_offenses_cps1.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
303452,531405,11,2004-07-22 00:00:00,2004-08-24,POLK,405341.0,10001,COCAINE - POSSESSION
521822,C04163,1,2007-07-17 00:00:00,2010-01-11,LAKE,901582.0,20000,ACQUIRE PROP. F/RACKETEERING
148208,195298,3,1994-07-12 00:00:00,1995-09-08,MIAMI-DADE,9425369.0,250000,BURGLARY ASSAULT ANY PERSON
408829,809515,15,2018-10-04 00:00:00,2019-07-19,MARTIN,1801400.0,20600,INTIMIDATE/FORCE WITNESS
893480,P41198,3,2009-01-18 00:00:00,2011-06-09,ESCAMBIA,901632.0,10103,FORGERY/UTTERING

In [49]:
# Inmate_release_offenses_CPS: Current prison offenses for these released inmates
df_inmate_release_offenses_cps2 = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_offenses_cps2.XLSX")

In [50]:
df_inmate_release_offenses_cps2.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
4792,S15546,12,2019-02-14,2019-10-28,SARASOTA,1904535.0,20300,UNAUTH POSS/USE OF DL/ID
182161,W45399,4,2012-09-10,2015-01-29,PALM BEACH,1210886.0,20600,FEL/DELI W/GUN/CONC WPN/AMMO
235445,Y18101,24,2001-06-13,2007-11-01,COLLIER,101966.0,10001,UTTER FORGED INSTRUMENT
127678,U55693,1,2016-01-21,2018-05-01,CITRUS,1600098.0,20000,"GRAND THEFT,300 L/5,000"
255195,Y50646,1,2012-03-28,2015-06-01,LEE,1215444.0,10300,POSS.CONTROL.SUBS/OTHER

In [51]:
# Inmate_release_offenses_prpr: Prior prison offenses for these released inmates
df_inmate_release_offenses_prpr = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_offenses_prpr.XLSX")

In [52]:
df_inmate_release_offenses_prpr.sample(5)

,DCNumber,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
260946,324272,4,1996-12-20 00:00:00,1999-06-04,ORANGE,9615749.0,20918,BATT.LEO/FIRFGT/EMS/ETC.
597192,913264,9,1991-10-01 00:00:00,1992-05-26,MIAMI-DADE,9135247.0,70000,POSS.FIREARM BY FELON
73321,090602,13,1987-09-03 00:00:00,1988-02-15,SEMINOLE,8701883.0,50000,BURGUNOCCSTRUC/CV OR ATT.
34057,059362,3,1986-08-21 00:00:00,1986-12-08,ST. LUCIE,8602071.0,10600,COCAINE-POSSESS
432853,595169,1,1978-06-27 00:00:00,1983-07-07,PALM BEACH,7801547.0,10001,BURGUNOCCSTRUC/CV OR ATT.

In [53]:
# Inmate_release_residence: Release plan address for these released inmates
df_inmate_release_residence = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_residence.XLSX")

In [54]:
df_inmate_release_residence.sample(5)

,DCNumber,AddressLine1,AddressLine2,City,State,ZipCode,Country
83663,405316,3564 WILLIAMS AVE.,NaN,"MIAMI,FL 33133",FL,33133,NaN
315936,Q23695,926 PELHAM AVE.,NaN,"GRACEVILLE, FL 32440",FL,32440,NaN
64639,272173,400 S EUCALYPTUS ST,NaN,"SEBRING, FL 33870",FL,33870,NaN
98174,511023,1434 E. ESTELLE ST APT C,NaN,"TAMPA, FL. 33605",FL,33605,NaN
248376,K55282,365 NE SURFSIDE AVE,NaN,"PT ST LUCIE, FL 34983",FL,34983,NaN

In [55]:
# Inmate_release_detainers: Detainers for these released inmates
df_inmate_release_detainers = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_detainer.XLSX")

In [56]:
df_inmate_release_detainers.sample(5)

,DCNumber,Authority,DetainerDate,RemovalDate,SequenceNo,detainertype_descr
91980,580978,ALBANY PD,1999-03-22 00:00:00,1999-06-18 00:00:00,1,DETAIN
267861,362076,NTFY: 100-BARTOW P&P,1998-03-13 00:00:00,2002-03-03 00:00:00,3,NTFY/P&P
138480,E08570,SEMINOLE CO SO,2001-04-04 00:00:00,2001-04-06 00:00:00,1,DETAIN
122329,884142,POLK CO. JAIL,1994-09-15 00:00:00,1998-10-07 00:00:00,1,DETAIN
310425,K10032,SP15.9MO F/B 1YR PRB,2106-05-05 00:00:00,NaN,1,NTFY/P&P

In [57]:
# Inmate_release_incarhist: Incarceration history for these released inmates
df_inmate_release_incarhist = pd.read_excel("../data/source/FL-OBIS/release/Inmate_Release_Apr_2022_incarhist.XLSX")

In [58]:
df_inmate_release_incarhist.sample(5)

       DCNumber ReceiptDate ReleaseDate
528955   H10464  2000-07-25  2009-10-02
83294    113935  1997-04-09  1998-01-21
233449   391491  1982-11-16  1985-11-01
243634   418711  2006-11-08  2014-10-19
806356   X24589  2003-02-20  2003-08-07

In [62]:
df_release = pd.merge(df_inmate_release_root, df_inmate_release_residence, on='DCNumber', how='outer')
df_release.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,AddressLine1,AddressLine2,City,State,ZipCode,Country
229393,H40649,SMITH,TSHAUMBE,J,NaN,B,M,1992-12-29,2015-06-01,valid release date,BLACK,MINIMUM,LAKE CITY C.F.,302 SOUTH OAK AVE,NaN,"FORT MEADE, FL 33841",FL,33841,NaN
41954,158095,GARCIA,IVETE,NaN,NaN,W,F,1986-05-02,2018-09-15,valid release date,WHITE,COMMUNITY,HOLLYWOOD C.R.C.,6950 FILMOR STREET,NaN,"HOLLYWOOD, FLORIDA 33024",FL,33024,NaN

In [63]:
df_release.shape

(435541, 19)

In [64]:
df_release = pd.merge(df_release, df_inmate_release_offenses_cps1, on='DCNumber', how='outer')
df_release.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
1054618,W02186,GRIER,HAL,B,NaN,W,M,1980-03-19,2005-07-16,valid release date,WHITE,MEDIUM,GULF C.I.- ANNEX,1919 E 2ND STREET,NaN,"EDMOND, OK 73003",OK,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
240252,403175,DIXON,CARL,NaN,NaN,B,M,1957-01-29,2001-07-30,valid release date,BLACK,MINIMUM,GULF C.I.,19705 S.W. 119TH PLACE,NaN,"MIAMI, FL. 33177",FL,33177,NaN,14.0,1997-10-25 00:00:00,1999-02-26,MIAMI-DADE,9734297.0,30000.0,COCAINE - POSSESSION

In [65]:
df_release.shape

(1090864, 26)

In [66]:
df_release = pd.merge(df_release, df_inmate_release_offenses_cps2, on='DCNumber', how='outer')
df_release.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence_x,OffenseDate_x,DateAdjudicated_x,County_x,CaseNumber_x,prisonterm_x,adjudicationcharge_descr_x,Sequence_y,OffenseDate_y,DateAdjudicated_y,County_y,CaseNumber_y,prisonterm_y,adjudicationcharge_descr_y
493643,B09079,KESSLER,JARED,W,NaN,W,M,1990-02-20,2013-12-01,valid release date,WHITE,MINIMUM,DADE C.I.,223 NE 19TH AVE #1,NaN,"POMPANO BCH, FL 33061",FL,33061,NaN,1.0,2009-09-09 00:00:00,2010-11-01,PALM BEACH,911393.0,40600.0,POSS.CONTROL.SUBS/OTHER,NaN,NaT,NaT,NaN,NaN,NaN,NaN
336401,605537,ARCE,JOSE,M,NaN,W,M,1966-09-28,2008-04-09,valid release date,WHITE,CLOSE,CENTRAL OFFICE,3393 BALTIC SEA BLVD,NaN,"TAVARES, FL 32778",FL,32778,NaN,10.0,1996-08-28 00:00:00,1997-02-21,PALM BEACH,9609653.0,41100.0,ROBB. NO GUN/DDLY.WPN,NaN,NaT,NaT,NaN,NaN,NaN,NaN

In [67]:
df_release.shape

(1263193, 33)

In [68]:
df_release = pd.merge(df_release, df_inmate_release_offenses_prpr, on='DCNumber', how='outer')
df_release.sample(2)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence_x,OffenseDate_x,DateAdjudicated_x,County_x,CaseNumber_x,prisonterm_x,adjudicationcharge_descr_x,Sequence_y,OffenseDate_y,DateAdjudicated_y,County_y,CaseNumber_y,prisonterm_y,adjudicationcharge_descr_y,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr
2428335,G08913,WINDHAM,RAY,N,NaN,W,M,1984-02-04,2021-02-01,valid release date,WHITE,MEDIUM,CFRC-EAST,297 IVY ST,NaN,"MACCLENNY,FL,32063",FL,32063,NaN,4.0,2020-02-27 00:00:00,2020-06-09,BAKER,2000128.0,314.0,POSS.DRUG PARAPHERNA.-MISD,NaN,NaT,NaT,NaN,NaN,NaN,NaN,1.0,2002-06-29 00:00:00,2005-11-28,BAKER,200218.0,30000.0,L/L BATTERY V 12-15 YO
1798089,734435,THOMPSON,HAROLD,L,NaN,W,M,1960-06-08,2019-04-10,valid release date,WHITE,MEDIUM,CFRC-MAIN,5715 NUTMEG AVENUE,NaN,"SARASOTA, FL 34231",FL,34231,NaN,11.0,2018-03-14 00:00:00,2018-12-17,SARASOTA,1804991.0,10001.0,TRAFFIC IN STOLEN PROPERTY,NaN,NaT,NaT,NaN,NaN,NaN,NaN,2.0,1988-08-21 00:00:00,1989-06-02,SARASOTA,8802496.0,50000.0,AGG BATTERY/W/DEADLY WEAPON

In [69]:
df_release.shape

(3980146, 40)

-----

## Filter by Type of Crime

In [ ]:
#Summing by buzzword and date
# df_reshaped = df_reshaped.groupby(['date', 'buzzword'])['value'].sum().reset_index()

In [ ]:
# df_offender.groupby(['adjudicationcharge_descr'])
# df_offender_theft = df_offender.groupby(['sadjudicationcharge_descr']).agg({'start_lat':'min','start_lng':'min','tripduration': 'count'}).reset_index()

In [90]:
df_offender_theft = df_offender[df_offender.adjudicationcharge_descr.str.contains("THEFT", case=False, na=False)]

In [92]:
df_offender_theft.shape

(51711, 28)

In [91]:
df_offender_theft.head()

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,SupervisionTerminationDate,ReceiptDate,supvtype_description,facility_description,supvstatus_description,race_descr,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,ProbationTerm,ParoleTerm,adjudicationcharge_descr
5,000059,PEREZ,JINO,NaN,NaN,W,M,1998-11-14,2023-02-12 00:00:00,2020-10-20,PROBATION FELONY,ORLANDO,ACTIVE SUSPENSE,WHITE,"3723 VISION BLVD, 2ND/3RD",FLOORS,ORLANDO,FL,32839.0,US,2.0,2016-08-11,2020-10-19,ORANGE,1714529.0,20325.0,0.0,"GRAND THEFT,300 L/5,000"
12,000092,HALL,AARON,LEE,NaN,W,M,1996-07-25,2021-09-06 00:00:00,2018-09-07,PROBATION FELONY,LAKE CITY,ABSCONDER/FUGITIVE,WHITE,ABSCONDER - SUWANNEE,NaN,NaN,NaN,NaN,US,2.0,2018-06-05,2018-09-07,SUWANNEE,1800346.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"
26,000175,ELMORE,CHAD,NaN,NaN,W,M,1982-10-20,2026-03-01 00:00:00,2021-03-02,PROBATION FELONY,JACKSONVILLE,ACTIVE SUSPENSE,WHITE,500 E ADAMS ST,DUVAL COUNTY JAIL,JACKSONVILLE,FL,32202.0,US,2.0,2018-06-01,2021-03-02,LAFAYETTE,2000022.0,50000.0,0.0,"GRAND THEFT,300 L/5,000"
30,000185,RUNION,DAVID,LEE,NaN,W,M,1982-12-14,2021-11-13 00:00:00,2018-11-14,PROBATION FELONY,GAINESVILLE,ACTIVE SUSPENSE,WHITE,9150 NE 80TH AVE,LEVY COUNTY JAIL,BRONSON,FL,32621.0,US,3.0,2018-07-03,2018-11-14,LEVY,1800504.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"
32,000185,RUNION,DAVID,LEE,NaN,W,M,1982-12-14,2021-11-13 00:00:00,2018-11-14,PROBATION FELONY,GAINESVILLE,ACTIVE SUSPENSE,WHITE,9150 NE 80TH AVE,LEVY COUNTY JAIL,BRONSON,FL,32621.0,US,5.0,2018-06-19,2018-11-14,LEVY,1800505.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"

In [98]:
df_offender_theft.adjudicationcharge_descr.sort_values().value_counts()

GRAND THEFT,300 L/5,000           21026
GRAND THEFT MOTOR VEHICLE          6831
GRAND THEFT $750+LT5K              4096
PETIT THEFT/3RD CONVICTION         3513
GRAND THEFT O/20,000 L/$100,00     3252
GRAND THEFT,$300 LESS &20,000      2537
GRAND THEFT $5KL/$10K              1677
GRAND THEFT FIREARM                1654
PETIT-THEFT-MISD                   1132
PETIT THEFT (MISD)                 1076
GRAND THEFT O/$100K                1034
GRAND THEFT $10K L/$20K             913
GR. THEFT $100-300 DWELLING         490
GRAND THEFT O/$100,000 1ST.DEG      400
THEFT>65YO>$300<$10K                262
RETAIL THEFT $300+                  228
THEFT STATE FUNDS $20K-100K         210
THEFT-STATE FUND $300-20K           154
THEFT:CONTROLLED SUBSTANCE          146
THEFT>65YO>$10K<$50K                133
ORGANIZES THEFT PROPERTY ECT.       127
CREDIT CARD THEFT-MISD.             103
LARCENY/GRAND THEFT                  84
RETAIL THEFT $750+                   69
THEFT>65YO>$50K                      66
GRAND THEFT FRM CONST.SITE           65
GRAND THEFT W/DAMAGE                 63
THEFT-STATE FUNDS $100K+             58
GRAND THEFT CARGO O/$50K             54
GRAND THEFT OF WILL                  47
THEFT COPPER/NONFER.METALS           29
ORG THEFT STOLEN PROP > 3K           28
THEFT FROM ESTAB.BY EMPLOY           27
GRAND THEFT FIRE EXTINGUISHER        26
RETAIL THEFT CONSPIRE                18
ORG RETAIL THEFT > 3K                18
ELCTRCL.SUB.STA.METALS,THEFT         16
THEFT LE EQUIP FROM EMER VEH         14
RETAIL THEFT $300+(2ND CONV.)        10
Retail Theft $750(2nd Conv.)          9
GRAND THEFT,CITRUS FRUIT              3
THEFT-STATE $$ U$300 3RD+CONV.        2
THEFT/DEST.ARCHEOLOG.SITE             2
GRAND THEFT OF STOP SIGN              2
THEFT AND STRIP VEHICLE               1
THEFT CABLE TV SERVICE                1
THEFT-STATE $$ U$1000 3RD+CONV        1
THEFT SEMI DEPLOY. BY LEO             1
THEFT OF US GOVT PROPERTY             1
THEFT - ANHYDROUS AMMONIA             1
VEHICLE THEFT/ILLEGAL USE             1
Name: adjudicationcharge_descr, dtype: int64

In [102]:
df_offender.adjudicationcharge_descr.sort_values().value_counts().head(50)

GRAND THEFT,300 L/5,000           21026
POSS.CONTROL.SUBS/OTHER           19975
BURGUNOCCSTRUC/CV OR ATT.         19931
POSS PHOTO ETC CHILD SEX PERF     13429
COCAINE - POSSESSION              10747
TRAFFIC IN STOLEN PROPERTY        10050
BURG/DWELL/OCCUP.CONVEY            7307
POSSESS METHAMPHETAMINE            7043
GRAND THEFT MOTOR VEHICLE          6831
AGG ASSLT-W/WPN NO INTENT TO K     6231
ROBB. GUN OR DEADLY WPN            6082
UTTER FORGED INSTRUMENT            5774
FRAUD USE OF PERSONAL ID           5326
POSS.DRUG PARAPHERNA.-MISD         5274
FEL/DELI W/GUN/CONC WPN/AMMO       4946
COCAINE-SALE/MANUF/DELIV.          4863
FALS INF. TO PWNBRKR<$300          4588
CARRYING CONCEALED FIREARM         4338
BATT.LEO/FIRFGT/EMS/ETC.           4176
GRAND THEFT $750+LT5K              4096
DUI-MISD.                          3776
SIMPLEBATTERY-MISD                 3615
FELONY BATTERY                     3601
PETIT THEFT/3RD CONVICTION         3513
ROBB. NO GUN/DDLY.WPN              3333
RESISTING OFFICER W/VIOLEN.        3276
CRIMINAL MISCHIEF/PROP.DAMAGE      3255
GRAND THEFT O/20,000 L/$100,00     3252
MISDEMEANOR                        3177
FRAUD-CREDIT-CARD                  3134
AGG BATTERY/W/DEADLY WEAPON        3124
MARIJUANA-SALE/MANUF/DEL           2908
WILLFUL CHILD ABUSE                2684
DRIV W/LIC S/R/C/D FELONY          2683
POSS.MARIJUANA OVR 20 GRAMS        2632
FORGERY/UTTERING                   2628
RESIST.LEO/NO VIOL.-MISD.          2566
GRAND THEFT,$300 LESS &20,000      2537
2+ SIMPLE BATTERY                  2498
AGG BATTERY INTENDED HARM          2256
UTTERING FORGED BILLS              2179
BURGLARY,ARMED W/EXP. OR WEAPO     2031
SEX BAT BY ADULT/VCTM LT 12        2024
POSSES MARIJUANA-MISD              1997
FELONY DWLSR                       1994
BURGL UNOCC DWELLING               1940
ORG.FRAUD - UNDER $20,000          1907
S/M/D OTH SCH I & II               1905
L/L MOLEST V<12 OFF 18+            1893
FLEE/ELUDE LEO-FELONY              1862
Name: adjudicationcharge_descr, dtype: int64

##### Relevant Adjudication Charges

In [99]:
# GRAND THEFT,300 L/5,000           21026  <br>
# GRAND THEFT $750+LT5K              4096  <br>
# PETIT THEFT/3RD CONVICTION         3513  <br>
# GRAND THEFT,$300 LESS &20,000      2537 <br>
# PETIT-THEFT-MISD                   1132 <br>
# PETIT THEFT (MISD)                 1076 <br>
# THEFT>65YO>$300<$10K                262 <br>
# RETAIL THEFT $300+                  228 <br>
# ORGANIZES THEFT PROPERTY ECT.       127 <br>
# GRAND THEFT W/DAMAGE                 63 <br>
# RETAIL THEFT CONSPIRE                18 <br>
# RETAIL THEFT $300+(2ND CONV.)        10 <br>
# Retail Theft $750(2nd Conv.)          9 <br>
# GRAND THEFT,CITRUS FRUIT              3 <br>
# THEFT-STATE $$ U$300 3RD+CONV.        2 <br>

In [109]:
df_offender_theft_300_5000 = df_offender[df_offender.adjudicationcharge_descr.str.contains("GRAND THEFT,300 L/5,000", case=False, na=False)]

In [110]:
df_offender_theft_300_5000.head(100)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,SupervisionTerminationDate,ReceiptDate,supvtype_description,facility_description,supvstatus_description,race_descr,AddressLine1,AddressLine2,City,State,ZipCode,Country,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,ProbationTerm,ParoleTerm,adjudicationcharge_descr
5,000059,PEREZ,JINO,NaN,NaN,W,M,1998-11-14,2023-02-12 00:00:00,2020-10-20,PROBATION FELONY,ORLANDO,ACTIVE SUSPENSE,WHITE,"3723 VISION BLVD, 2ND/3RD",FLOORS,ORLANDO,FL,32839.0,US,2.0,2016-08-11,2020-10-19,ORANGE,1714529.0,20325.0,0.0,"GRAND THEFT,300 L/5,000"
12,000092,HALL,AARON,LEE,NaN,W,M,1996-07-25,2021-09-06 00:00:00,2018-09-07,PROBATION FELONY,LAKE CITY,ABSCONDER/FUGITIVE,WHITE,ABSCONDER - SUWANNEE,NaN,NaN,NaN,NaN,US,2.0,2018-06-05,2018-09-07,SUWANNEE,1800346.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"
26,000175,ELMORE,CHAD,NaN,NaN,W,M,1982-10-20,2026-03-01 00:00:00,2021-03-02,PROBATION FELONY,JACKSONVILLE,ACTIVE SUSPENSE,WHITE,500 E ADAMS ST,DUVAL COUNTY JAIL,JACKSONVILLE,FL,32202.0,US,2.0,2018-06-01,2021-03-02,LAFAYETTE,2000022.0,50000.0,0.0,"GRAND THEFT,300 L/5,000"
30,000185,RUNION,DAVID,LEE,NaN,W,M,1982-12-14,2021-11-13 00:00:00,2018-11-14,PROBATION FELONY,GAINESVILLE,ACTIVE SUSPENSE,WHITE,9150 NE 80TH AVE,LEVY COUNTY JAIL,BRONSON,FL,32621.0,US,3.0,2018-07-03,2018-11-14,LEVY,1800504.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"
32,000185,RUNION,DAVID,LEE,NaN,W,M,1982-12-14,2021-11-13 00:00:00,2018-11-14,PROBATION FELONY,GAINESVILLE,ACTIVE SUSPENSE,WHITE,9150 NE 80TH AVE,LEVY COUNTY JAIL,BRONSON,FL,32621.0,US,5.0,2018-06-19,2018-11-14,LEVY,1800505.0,30000.0,0.0,"GRAND THEFT,300 L/5,000"
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2081,051014,WILSON,RICKY,A,NaN,B,M,1959-01-08,2022-09-22 00:00:00,2020-10-15,CONDITIONAL REL.SUPERVISN,FT. LAUDERDALE,ACTIVE,BLACK,660 NW 23RD TER,NaN,POMPANO BEACH,FL,33069.0,US,1.0,2008-02-18,2012-03-21,MIAMI-DADE,806162.0,0.0,11107.0,"GRAND THEFT,300 L/5,000"
2082,051014,WILSON,RICKY,A,NaN,B,M,1959-01-08,2022-09-22 00:00:00,2020-10-15,CONDITIONAL REL.SUPERVISN,FT. LAUDERDALE,ACTIVE,BLACK,660 NW 23RD TER,NaN,POMPANO BEACH,FL,33069.0,US,2.0,2011-11-11,2012-03-21,MIAMI-DADE,1131209.0,0.0,11107.0,"GRAND THEFT,300 L/5,000"
2084,051014,WILSON,RICKY,A,NaN,B,M,1959-01-08,2022-09-22 00:00:00,2020-10-15,CONDITIONAL REL.SUPERVISN,FT. LAUDERDALE,ACTIVE,BLACK,660 NW 23RD TER,NaN,POMPANO BEACH,FL,33069.0,US,4.0,2011-11-28,2012-03-21,MIAMI-DADE,1131210.0,0.0,11107.0,"GRAND THEFT,300 L/5,000"
2085,051014,WILSON,RICKY,A,NaN,B,M,1959-01-08,2022-09-22 00:00:00,2020-10-15,CONDITIONAL REL.SUPERVISN,FT. LAUDERDALE,ACTIVE,BLACK,660 NW 23RD TER,NaN,POMPANO BEACH,FL,33069.0,US,5.0,2011-11-28,2012-03-21,MIAMI-DADE,1131210.0,0.0,11107.0,"GRAND THEFT,300 L/5,000"
2086,051014,WILSON,RICKY,A,NaN,B,M,1959-01-08,2022-09-22 00:00:00,2020-10-15,CONDITIONAL REL.SUPERVISN,FT. LAUDERDALE,ACTIVE,BLACK,660 NW 23RD TER,NaN,POMPANO BEACH,FL,33069.0,US,6.0,2011-12-01,2012-03-21,MIAMI-DADE,1131211.0,0.0,11107.0,"GRAND THEFT,300 L/5,000"

In [ ]:
# df_offender_theft_table = df_offender_theft.groupby(['adjudicationcharge_descr']).agg({'start_lat':'min','start_lng':'min','tripduration': 'count'}).reset_index()

In [89]:
df_offender.adjudicationcharge_descr.str.contains('THEFT', case=False, na=False)

0         False
1         False
2         False
3         False
4         False
          ...
381910    False
381911    False
381912    False
381913    False
381914    False
Name: adjudicationcharge_descr, Length: 381915, dtype: bool

In [84]:
df_active_theft = df_active[df_active.adjudicationcharge_descr.str.contains("THEFT", case=False, na=False)]
df_active_theft.sample(5)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
399656,T83127,MEDINA,JOSEPH,M,NaN,H,M,1990-12-17,2022-04-01 00:00:00,2020-12-07,valid release date,HISPANIC,CLOSE,AVON PARK C.I.,9.0,2020-02-23,2020-10-19,HILLSBOROUGH,2002487.0,10300.0,GRAND THEFT $750+LT5K,13C:1005843,2013-09-30 00:00:00,N,2019-10-22,1.0,NTFY/P&P
438868,W26050,ANDERSON,GEOFFREY,P,NaN,W,M,1984-08-08,2022-07-28 00:00:00,2020-09-16,valid release date,WHITE,COMMUNITY,TFF-Ft. PIERCE CRC,12.0,2019-07-31,2020-05-14,PALM BEACH,1911708.0,30000.0,"GRAND THEFT,300 L/5,000",BROWARD CO SO,2014-08-06 00:00:00,D,2015-06-29,1.0,DETAIN
305632,M12380,KEMP,EDWARD,Q,NaN,B,M,1980-06-22,2024-02-28 00:00:00,2022-01-28,valid release date,BLACK,MEDIUM,MARTIN C.I.,27.0,2018-12-20,2021-09-09,MIAMI-DADE,1825242.0,30000.0,"GRAND THEFT,300 L/5,000",MIAMI DADE CO SO,2012-12-10 00:00:00,D,2014-02-25,4.0,DETAIN
472569,Y61011,DILAN,CRISTIAN,NaN,NaN,W,M,1998-01-29,NaN,2021-11-24,life sentence,WHITE,CLOSE,MARTIN C.I.,1.0,2017-10-29,2021-09-10,LEE,1816658.0,50000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
238227,H05716,WRIGHT,RICO,A,NaN,B,M,1979-03-28,2022-10-27 00:00:00,1998-10-09,valid release date,BLACK,CLOSE,COLUMBIA ANNEX,7.0,1997-07-24,1998-08-21,POLK,9706985.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN

In [88]:
df_active_theft.adjudicationcharge_descr.value_counts()

GRAND THEFT,300 L/5,000           23292
GRAND THEFT MOTOR VEHICLE         10325
PETIT THEFT/3RD CONVICTION         5260
GRAND THEFT FIREARM                4495
GRAND THEFT $750+LT5K              2474
GR. THEFT $100-300 DWELLING        1921
GRAND THEFT O/20,000 L/$100,00     1413
GRAND THEFT,$300 LESS &20,000      1327
GRAND THEFT $5KL/$10K              1224
GRAND THEFT $10K L/$20K             856
GRAND THEFT W/DAMAGE                594
GRAND THEFT O/$100K                 474
RETAIL THEFT $300+                  159
THEFT>65YO>$300<$10K                152
ORGANIZES THEFT PROPERTY ECT.       110
THEFT:CONTROLLED SUBSTANCE           87
GRAND THEFT O/$100,000 1ST.DEG       66
THEFT>65YO>$10K<$50K                 42
RETAIL THEFT $750+                   42
THEFT>65YO>$50K                      40
GRAND THEFT FRM CONST.SITE           35
GRAND THEFT CARGO O/$50K             32
LARCENY/GRAND THEFT                  26
PETIT-THEFT-MISD                     13
ORG RETAIL THEFT > 3K                10
THEFT LE EQUIP FROM EMER VEH         10
GRAND THEFT FIRE EXTINGUISHER         9
RETAIL THEFT $300+(2ND CONV.)         8
THEFT COPPER/NONFER.METALS            8
Retail Theft $750(2nd Conv.)          4
THEFT STATE FUNDS $20K-100K           3
THEFT-STATE FUND $300-20K             3
THEFT SEMI DEPLOY. BY LEO             2
VEHICLE THEFT/ILLEGAL USE             2
THEFT FROM ESTAB.BY EMPLOY            2
THEFT-STATE FUNDS $100K+              1
CREDIT CARD THEFT-MISD.               1
THEFT-STATE $$ U$1000 3RD+CONV        1
THEFT-STATE $$ U$300 3RD+CONV.        1
GRAND THEFT OF STOP SIGN              1
Name: adjudicationcharge_descr, dtype: int64

**300-5000 Active Theft**

In [106]:
df_active_theft_300_5000 = df_active[df_active.adjudicationcharge_descr.str.contains("GRAND THEFT,300 L/5,000", case=False, na=False)]

In [108]:
df_active_theft_300_5000.head(50)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
40,000166,BATES,BILLIE,S,NaN,W,F,1990-03-26,2023-05-12 00:00:00,2018-11-01,valid release date,WHITE,CLOSE,LOWELL C.I.,3.0,2016-08-28,2018-10-17,INDIAN RIVER,1601219.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
519,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,5.0,2018-12-06,2021-04-21,BAY,1903985.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
520,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,6.0,2019-02-12,2021-04-21,BAY,1903986.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
521,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,7.0,2019-03-25,2021-04-21,BAY,1903988.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
527,010770,WINTHERS,BRYSON,C,NaN,W,M,1995-01-14,2024-05-23 00:00:00,2021-01-25,valid release date,WHITE,MINIMUM,COLUMBIA ANNEX,2.0,2019-02-23,2020-12-04,BAY,1901008.0,40000.0,"GRAND THEFT,300 L/5,000","140BAY 1YR CC,10YR",2020-12-04 00:00:00,N,NaT,1.0,NTFY/P&P
741,016450,FLEMING,TIMOTHY,NaN,NaN,B,M,1946-06-21,2027-02-10 00:00:00,2001-10-25,valid release date,BLACK,MINIMUM,SUWANNEE C.I. ANNEX,7.0,2000-07-25,2001-04-20,BROWARD,13134.0,100000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
860,019929,GADSON,JOHN,L,NaN,B,M,1948-01-16,2033-09-13 00:00:00,2002-08-08,valid release date,BLACK,CLOSE,MARTIN C.I.,24.0,2001-02-01,2002-07-17,INDIAN RIVER,100237.0,50000.0,"GRAND THEFT,300 L/5,000",LEE CO. SO.,1992-09-14 00:00:00,D,1993-11-10,2.0,DETAIN
861,019929,GADSON,JOHN,L,NaN,B,M,1948-01-16,2033-09-13 00:00:00,2002-08-08,valid release date,BLACK,CLOSE,MARTIN C.I.,24.0,2001-02-01,2002-07-17,INDIAN RIVER,100237.0,50000.0,"GRAND THEFT,300 L/5,000",PALM BEACH CO SO,2009-10-14 00:00:00,D,NaT,3.0,DETAIN
862,019929,GADSON,JOHN,L,NaN,B,M,1948-01-16,2033-09-13 00:00:00,2002-08-08,valid release date,BLACK,CLOSE,MARTIN C.I.,24.0,2001-02-01,2002-07-17,INDIAN RIVER,100237.0,50000.0,"GRAND THEFT,300 L/5,000",150 WPB P & P,1992-01-28 00:00:00,N,1993-11-16,1.0,NTFY/P&P
882,020035,ALTIZER,JESSE,J,NaN,W,M,1999-06-18,2026-11-03 00:00:00,2018-08-07,valid release date,WHITE,MINIMUM,GULF C.I.,4.0,2017-08-09,2018-07-30,BREVARD,1739677.0,50000.0,"GRAND THEFT,300 L/5,000",182 COCOA P & P,2018-07-30 00:00:00,N,NaT,1.0,NTFY/P&P
909,020273,BAKER,ROQUAN,M,NaN,B,M,2000-03-27,2024-01-08 00:00:00,2021-06-16,valid release date,BLACK,MEDIUM,LAKE CITY C.F.,2.0,2018-11-02,2021-06-03,PALM BEACH,1811017.0,30400.0,"GRAND THEFT,300 L/5,000",PALM BEACH CO SO,2021-09-07 00:00:00,D,NaT,2.0,DETAIN
910,020273,BAKER,ROQUAN,M,NaN,B,M,2000-03-27,2024-01-08 00:00:00,2021-06-16,valid release date,BLACK,MEDIUM,LAKE CITY C.F.,2.0,2018-11-02,2021-06-03,PALM BEACH,1811017.0,30400.0,"GRAND THEFT,300 L/5,000",PALM BEACH CO SO,2021-09-01 00:00:00,D,NaT,1.0,DETAIN
1378,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,48.0,1998-12-04,2002-02-12,MIAMI-DADE,9920343.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1380,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,50.0,1998-12-21,2002-02-12,MIAMI-DADE,9920344.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1386,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,56.0,1999-03-29,2002-02-12,MIAMI-DADE,9920356.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1390,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,60.0,1999-04-28,2002-02-12,MIAMI-DADE,9920359.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1394,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,64.0,1999-04-01,2002-02-12,MIAMI-DADE,9920363.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1396,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,66.0,1999-05-13,2002-02-12,MIAMI-DADE,9920366.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1399,025813,WADE,WALLACE,NaN,NaN,B,M,1952-12-29,NaN,2002-05-17,life sentence,BLACK,CLOSE,MARTIN C.I.,69.0,1999-05-14,2002-02-12,MIAMI-DADE,9920368.0,50000.0,"GRAND THEFT,300 L/5,000",METRO DADE PD,1986-08-29 00:00:00,D,1987-04-20,1.0,DETAIN
1616,028047,ISREAL,ELIJAH,NaN,NaN,B,M,1952-02-23,2028-07-14 00:00:00,2015-01-27,valid release date,BLACK,MINIMUM,SOUTH BAY C.F.,26.0,2013-06-23,2015-01-20,BROWARD,1308820.0,100000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
1626,028270,BETHUNE,ELIJAH,NaN,NaN,B,M,1952-11-04,2022-05-08 00:00:00,2010-09-21,valid release date,BLACK,MINIMUM,R.M.C.- MAIN UNIT,16.0,2009-07-06,2010-06-17,PINELLAS,916943.0,50000.0,"GRAND THEFT,300 L/5,000",06CPPI;9014896,1991-08-23 00:00:00,N,1999-06-21,1.0,NTFY/P&P
1669,028658,DAVIS,THEODORE,NaN,JR.,B,M,1943-11-11,NaN,1993-07-13,life sentence,BLACK,CLOSE,MADISON C.I.,7.0,1995-02-03,1995-10-20,HILLSBOROUGH,9511604.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
1698,029026,MOSLEY,HOMER,NaN,JR,B,M,1950-10-01,2033-01-12 00:00:00,2015-11-16,valid release date,BLACK,MEDIUM,PUTNAM C.I.,15.0,2015-05-14,2015-11-05,ALACHUA,1501954.0,50000.0,"GRAND THEFT,300 L/5,000",POSS USE ETC. DRUG P,1991-01-09 00:00:00,D,1991-01-18,2.0,DETAIN
1699,029026,MOSLEY,HOMER,NaN,JR,B,M,1950-10-01,2033-01-12 00:00:00,2015-11-16,valid release date,BLACK,MEDIUM,PUTNAM C.I.,15.0,2015-05-14,2015-11-05,ALACHUA,1501954.0,50000.0,"GRAND THEFT,300 L/5,000",ALACHUA CO.SO.90-472,1991-01-08 00:00:00,D,1991-01-18,1.0,DETAIN
1881,030573,GATELEY,TOMMY LEE,R,NaN,W,M,1989-09-26,2023-04-22 00:00:00,2021-05-17,valid release date,WHITE,MEDIUM,SANTA ROSA C.I.,4.0,2019-05-31,2021-05-10,VOLUSIA,1912556.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
1961,031251,STAFFORD,TERRY,D,NaN,B,M,1953-01-10,2023-07-24 00:00:00,2015-12-10,valid release date,BLACK,CLOSE,DADE C.I.,5.0,2015-01-19,2015-11-03,MARION,1500214.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
1965,031251,STAFFORD,TERRY,D,NaN,B,M,1953-01-10,2023-07-24 00:00:00,2015-12-10,valid release date,BLACK,CLOSE,DADE C.I.,9.0,2015-01-05,2015-11-03,MARION,1500306.0,100000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
2177,032978,REGAN,JOHNNIE,L,NaN,B,M,1954-10-07,2028-06-03 00:00:00,2008-10-20,valid release date,BLACK,MEDIUM,MOORE HAVEN C.F.,8.0,2006-01-17,2008-07-01,MIAMI-DADE,708991.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
2195,033310,ROGERS,LARRY,NaN,NaN,B,M,1952-05-28,NaN,1972-02-11,life sentence,BLACK,MEDIUM,EVERGLADES C.I.,5.0,1999-12-01,2001-01-05,BROWARD,1355.0,20000.0,"GRAND THEFT,300 L/5,000","SO BROWARD CO,FLA",1982-05-25 00:00:00,D,1990-02-16,1.0,DETAIN
2196,033310,ROGERS,LARRY,NaN,NaN,B,M,1952-05-28,NaN,1972-02-11,life sentence,BLACK,MEDIUM,EVERGLADES C.I.,5.0,1999-12-01,2001-01-05,BROWARD,1355.0,20000.0,"GRAND THEFT,300 L/5,000",17-0 BROW,2001-02-21 00:00:00,N,NaT,2.0,NTFY/P&P
2294,034009,MUHAMMAD,ALBAQI,B,NaN,B,M,1953-09-05,2034-04-09 00:00:00,2007-02-15,valid release date,BLACK,MEDIUM,CROSS CITY EAST UNIT,17.0,2012-08-16,2012-10-17,DUVAL,1208026.0,21015.0,"GRAND THEFT,300 L/5,000",JACKSONVILLE SO,2004-08-16 00:00:00,D,2004-08-27,2.0,DETAIN
2295,034009,MUHAMMAD,ALBAQI,B,NaN,B,M,1953-09-05,2034-04-09 00:00:00,2007-02-15,valid release date,BLACK,MEDIUM,CROSS CITY EAST UNIT,17.0,2012-08-16,2012-10-17,DUVAL,1208026.0,21015.0,"GRAND THEFT,300 L/5,000",DUVAL CO.S.O. 1YR.,1985-11-22 00:00:00,D,1986-11-17,1.0,DETAIN
2557,036376,LAWSON,MARK,A,NaN,W,M,1955-01-10,NaN,2004-11-23,life sentence,WHITE,CLOSE,UNION C.I.,14.0,2003-09-01,2004-11-09,PINELLAS,402086.0,20900.0,"GRAND THEFT,300 L/5,000","SO BRADFORD CO,FLA",1983-09-20 00:00:00,D,1984-01-13,1.0,DETAIN
2687,037580,DEAN,WILLIE,A,NaN,B,M,1954-03-12,2024-08-02 00:00:00,2009-04-15,valid release date,BLACK,CLOSE,EVERGLADES C.I.,8.0,2005-06-28,2009-03-24,MIAMI-DADE,719492.0,100000.0,"GRAND THEFT,300 L/5,000",07-19492/07-40771,2009-04-02 00:00:00,N,NaT,1.0,NTFY/P&P
2707,037803,CAMPBELL,FRED,E,NaN,W,M,1955-10-06,2022-04-08 00:00:00,2020-03-11,valid release date,WHITE,CLOSE,EVERGLADES C.I.,22.0,2017-12-12,2020-02-21,MIAMI-DADE,1723461.0,50000.0,"GRAND THEFT,300 L/5,000",BROWARD CO SO,2020-03-24 00:00:00,D,NaT,2.0,DETAIN
2708,037803,CAMPBELL,FRED,E,NaN,W,M,1955-10-06,2022-04-08 00:00:00,2020-03-11,valid release date,WHITE,CLOSE,EVERGLADES C.I.,22.0,2017-12-12,2020-02-21,MIAMI-DADE,1723461.0,50000.0,"GRAND THEFT,300 L/5,000",US MARSHAL MIAMI,1989-05-26 00:00:00,D,2009-12-02,1.0,DETAIN
3139,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,31.0,2019-01-20,2019-08-22,PINELLAS,1901248.0,50720.0,"GRAND THEFT,300 L/5,000",PINELLAS CO SO,2007-02-16 00:00:00,D,2007-03-09,2.0,DETAIN
3140,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,31.0,2019-01-20,2019-08-22,PINELLAS,1901248.0,50720.0,"GRAND THEFT,300 L/5,000",NTFY:06-C PPI,1991-05-31 00:00:00,N,1997-05-30,1.0,NTFY/P&P
3151,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,37.0,2019-07-09,2019-08-22,PINELLAS,1908924.0,50720.0,"GRAND THEFT,300 L/5,000",PINELLAS CO SO,2007-02-16 00:00:00,D,2007-03-09,2.0,DETAIN
3152,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,37.0,2019-07-09,2019-08-22,PINELLAS,1908924.0,50720.0,"GRAND THEFT,300 L/5,000",NTFY:06-C PPI,1991-05-31 00:00:00,N,1997-05-30,1.0,NTFY/P&P
3153,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,38.0,2019-06-09,2019-08-22,PINELLAS,1908924.0,50720.0,"GRAND THEFT,300 L/5,000",PINELLAS CO SO,2007-02-16 00:00:00,D,2007-03-09,2.0,DETAIN
3154,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,38.0,2019-06-09,2019-08-22,PINELLAS,1908924.0,50720.0,"GRAND THEFT,300 L/5,000",NTFY:06-C PPI,1991-05-31 00:00:00,N,1997-05-30,1.0,NTFY/P&P
3155,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,39.0,2019-07-25,2019-08-22,PINELLAS,1908925.0,50720.0,"GRAND THEFT,300 L/5,000",PINELLAS CO SO,2007-02-16 00:00:00,D,2007-03-09,2.0,DETAIN
3156,040789,MILLER,RICHARD,NaN,NaN,B,M,1954-08-07,2024-06-19 00:00:00,2019-11-14,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,39.0,2019-07-25,2019-08-22,PINELLAS,1908925.0,50720.0,"GRAND THEFT,300 L/5,000",NTFY:06-C PPI,1991-05-31 00:00:00,N,1997-05-30,1.0,NTFY/P&P
3208,041051,SANDERS,ROBERT,M,NaN,W,M,1956-03-20,2023-12-13 00:00:00,2012-02-22,valid release date,WHITE,MEDIUM,UNION C.I.,10.0,2010-02-24,2012-02-13,MONROE,1000164.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
3412,042108,JONES,BOBBY,J,NaN,B,M,1953-03-08,2024-05-31 00:00:00,2009-10-01,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,14.0,2008-07-03,2009-09-21,BREVARD,837764.0,50000.0,"GRAND THEFT,300 L/5,000",NTFY:BROW.BD.CO.COM.,1986-04-08 00:00:00,N,1992-05-11,1.0,NTFY/P&P
3413,042108,JONES,BOBBY,J,NaN,B,M,1953-03-08,2024-05-31 00:00:00,2009-10-01,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,14.0,2008-07-03,2009-09-21,BREVARD,837764.0,50000.0,"GRAND THEFT,300 L/5,000",NTFY:18-0 TVILLE PP,1993-10-25 00:00:00,N,1997-04-01,3.0,NTFY/P&P
3414,042108,JONES,BOBBY,J,NaN,B,M,1953-03-08,2024-05-31 00:00:00,2009-10-01,valid release date,BLACK,MEDIUM,NWFRC MAIN UNIT.,14.0,2008-07-03,2009-09-21,BREVARD,837764.0,50000.0,"GRAND THEFT,300 L/5,000",BREVARD CO P&P,1986-08-25 00:00:00,N,1997-04-01,2.0,NTFY/P&P
3503,042640,LAWS,BOBBY,L,NaN,B,M,1954-10-28,2022-05-25 00:00:00,2017-10-23,valid release date,BLACK,MINIMUM,EVERGLADES C.I.,16.0,2017-07-04,2017-09-26,PALM BEACH,1706643.0,10001.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
3604,043592,HOYT,AMOS,NaN,NaN,B,M,1955-02-16,NaN,1974-11-04,life sentence,BLACK,MINIMUM,MOORE HAVEN C.F.,4.0,2006-12-28,2008-07-10,BREVARD,668920.0,30000.0,"GRAND THEFT,300 L/5,000",BREVARD CO SO,2007-10-19 00:00:00,D,2008-02-12,1.0,DETAIN

In [128]:
df_active_theft_300_5000_drop = df_active_theft_300_5000.drop_duplicates(subset=['DCNumber'])
df_active_theft_300_5000_drop.shape

(6165, 27)

In [129]:
df_active_theft_300_5000_drop.Race.value_counts()

W    3281
B    2608
H     259
U      14
I       3
Name: Race, dtype: int64

In [130]:
df_active_theft_300_5000_drop.Race.value_counts(normalize=True)

W    0.532198
B    0.423033
H    0.042011
U    0.002271
I    0.000487
Name: Race, dtype: float64

**750-5000 Active Theft**

In [136]:
df_active_theft_750_5000 = df_active[df_active.adjudicationcharge_descr.str.contains("GRAND THEFT $750+LT5K", case=False, na=False)]

In [137]:
df_active_theft_750_5000.head(50)

Empty DataFrame
Columns: [DCNumber, LastName, FirstName, MiddleName, NameSuffix, Race, Sex, BirthDate, PrisonReleaseDate, ReceiptDate, releasedateflag_descr, race_descr, custody_description, FACILITY_description, Sequence, OffenseDate, DateAdjudicated, County, CaseNumber, prisonterm, adjudicationcharge_descr, Authority, DetainerDate, DetainerType, RemovalDate, SequenceNo, detainertype_descr]
Index: []

In [133]:
df_active_theft_750_5000_drop = df_active_theft_750_5000.drop_duplicates(subset=['DCNumber'])
df_active_theft_750_5000_drop.shape

(0, 27)

In [134]:
df_active_theft_750_5000_drop.Race.value_counts()

Series([], Name: Race, dtype: int64)

In [148]:
df_active_theft_750_5000_drop.Race.value_counts(normalize=True)

Series([], Name: Race, dtype: float64)

**Petit Theft Misdemeanor**

In [111]:
df_active_theft_PETIT_THEFT_MISD = df_active[df_active.adjudicationcharge_descr.str.contains("PETIT-THEFT-MISD", case=False, na=False)]

In [112]:
df_active_theft_PETIT_THEFT_MISD.head(50)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
9492,070840,PITT,DEMARCUS,J,NaN,B,M,2000-03-03,2025-08-22 00:00:00,2021-07-01,valid release date,BLACK,CLOSE,BLACKWATER C.F.,12.0,2019-02-18,2021-06-07,LAKE,1900517.0,50106.0,PETIT-THEFT-MISD,NaN,NaN,NaN,NaT,NaN,NaN
42115,135217,APONTE,YOVANY,L,NaN,H,M,1992-08-23,2032-12-29 00:00:00,2020-05-13,valid release date,HISPANIC,MEDIUM,WAKULLA C.I.,21.0,2018-04-13,2020-02-21,POLK,1807311.0,150000.0,PETIT-THEFT-MISD,LAKE CO SO,2020-05-27 00:00:00,D,NaT,1.0,DETAIN
231435,G22157,JONES,DEDRICK,D,NaN,B,M,1991-08-11,2032-02-25 00:00:00,2015-04-30,valid release date,BLACK,CLOSE,OKALOOSA C.I.,10.0,2010-11-05,2015-04-16,BAKER,1000541.0,50000.0,PETIT-THEFT-MISD,NOTIFY 082 120 DAYS,2012-11-27 00:00:00,N,NaT,1.0,NTFY/P&P
231436,G22157,JONES,DEDRICK,D,NaN,B,M,1991-08-11,2032-02-25 00:00:00,2015-04-30,valid release date,BLACK,CLOSE,OKALOOSA C.I.,10.0,2010-11-05,2015-04-16,BAKER,1000541.0,50000.0,PETIT-THEFT-MISD,NOTIFY 082 20 YRS FB,2015-04-16 00:00:00,N,NaT,2.0,NTFY/P&P
232906,G27674,JACKSON,CODY,W,NaN,W,M,2000-03-24,2022-07-17 00:00:00,2019-09-24,valid release date,WHITE,MEDIUM,HOLMES C.I.,5.0,2017-09-11,2019-09-11,LEVY,1700729.0,50000.0,PETIT-THEFT-MISD,NaN,NaN,NaN,NaT,NaN,NaN
236624,G81080,GEORGES,GIOVANNI,NaN,NaN,B,M,1998-02-07,2022-07-10 00:00:00,2021-04-13,valid release date,BLACK,CLOSE,AVON PARK C.I.,3.0,2019-07-29,2021-03-08,OSCEOLA,1902730.0,10600.0,PETIT-THEFT-MISD,094 KISSIMMEE INTAKE,2021-03-08 00:00:00,N,NaT,1.0,NTFY/P&P
236625,G81080,GEORGES,GIOVANNI,NaN,NaN,B,M,1998-02-07,2022-07-10 00:00:00,2021-04-13,valid release date,BLACK,CLOSE,AVON PARK C.I.,4.0,2019-07-29,2021-03-08,OSCEOLA,1902730.0,10600.0,PETIT-THEFT-MISD,094 KISSIMMEE INTAKE,2021-03-08 00:00:00,N,NaT,1.0,NTFY/P&P
290747,L03959,BELL,DEREK,L,NaN,B,M,1978-05-04,2034-05-14 00:00:00,2020-02-27,valid release date,BLACK,MEDIUM,MARTIN C.I.,83.0,2015-08-04,2020-01-17,BROWARD,1700621.0,30323.0,PETIT-THEFT-MISD,17-B P & P,2020-01-17 00:00:00,N,NaT,2.0,NTFY/P&P
290748,L03959,BELL,DEREK,L,NaN,B,M,1978-05-04,2034-05-14 00:00:00,2020-02-27,valid release date,BLACK,MEDIUM,MARTIN C.I.,83.0,2015-08-04,2020-01-17,BROWARD,1700621.0,30323.0,PETIT-THEFT-MISD,170-P&P,1996-09-26 00:00:00,N,1998-06-23,1.0,NTFY/P&P
290749,L03959,BELL,DEREK,L,NaN,B,M,1978-05-04,2034-05-14 00:00:00,2020-02-27,valid release date,BLACK,MEDIUM,MARTIN C.I.,84.0,2016-08-03,2020-01-17,BROWARD,1700621.0,30323.0,PETIT-THEFT-MISD,17-B P & P,2020-01-17 00:00:00,N,NaT,2.0,NTFY/P&P
290750,L03959,BELL,DEREK,L,NaN,B,M,1978-05-04,2034-05-14 00:00:00,2020-02-27,valid release date,BLACK,MEDIUM,MARTIN C.I.,84.0,2016-08-03,2020-01-17,BROWARD,1700621.0,30323.0,PETIT-THEFT-MISD,170-P&P,1996-09-26 00:00:00,N,1998-06-23,1.0,NTFY/P&P
314598,M64754,DELEON,CARLOS,NaN,NaN,W,M,1989-01-10,2023-11-06 00:00:00,2021-04-01,valid release date,WHITE,MEDIUM,APALACHEE WEST UNIT,9.0,2019-01-15,2020-10-15,MIAMI-DADE,1901751.0,50000.0,PETIT-THEFT-MISD,MONROE CO SO,2021-04-16 00:00:00,D,NaT,2.0,DETAIN
314599,M64754,DELEON,CARLOS,NaN,NaN,W,M,1989-01-10,2023-11-06 00:00:00,2021-04-01,valid release date,WHITE,MEDIUM,APALACHEE WEST UNIT,9.0,2019-01-15,2020-10-15,MIAMI-DADE,1901751.0,50000.0,PETIT-THEFT-MISD,CS#0917054 1035024,2012-06-12 00:00:00,N,2012-12-01,1.0,NTFY/P&P

In [120]:
df_active_theft_PETIT_THEFT_MISD.shape

(13, 27)

In [126]:
df_active_theft_PETIT_THEFT_MISD_drop = df_active_theft_PETIT_THEFT_MISD.drop_duplicates(subset=['DCNumber'])
df_active_theft_PETIT_THEFT_MISD_drop.head(20)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
9492,070840,PITT,DEMARCUS,J,NaN,B,M,2000-03-03,2025-08-22 00:00:00,2021-07-01,valid release date,BLACK,CLOSE,BLACKWATER C.F.,12.0,2019-02-18,2021-06-07,LAKE,1900517.0,50106.0,PETIT-THEFT-MISD,NaN,NaN,NaN,NaT,NaN,NaN
42115,135217,APONTE,YOVANY,L,NaN,H,M,1992-08-23,2032-12-29 00:00:00,2020-05-13,valid release date,HISPANIC,MEDIUM,WAKULLA C.I.,21.0,2018-04-13,2020-02-21,POLK,1807311.0,150000.0,PETIT-THEFT-MISD,LAKE CO SO,2020-05-27 00:00:00,D,NaT,1.0,DETAIN
231435,G22157,JONES,DEDRICK,D,NaN,B,M,1991-08-11,2032-02-25 00:00:00,2015-04-30,valid release date,BLACK,CLOSE,OKALOOSA C.I.,10.0,2010-11-05,2015-04-16,BAKER,1000541.0,50000.0,PETIT-THEFT-MISD,NOTIFY 082 120 DAYS,2012-11-27 00:00:00,N,NaT,1.0,NTFY/P&P
232906,G27674,JACKSON,CODY,W,NaN,W,M,2000-03-24,2022-07-17 00:00:00,2019-09-24,valid release date,WHITE,MEDIUM,HOLMES C.I.,5.0,2017-09-11,2019-09-11,LEVY,1700729.0,50000.0,PETIT-THEFT-MISD,NaN,NaN,NaN,NaT,NaN,NaN
236624,G81080,GEORGES,GIOVANNI,NaN,NaN,B,M,1998-02-07,2022-07-10 00:00:00,2021-04-13,valid release date,BLACK,CLOSE,AVON PARK C.I.,3.0,2019-07-29,2021-03-08,OSCEOLA,1902730.0,10600.0,PETIT-THEFT-MISD,094 KISSIMMEE INTAKE,2021-03-08 00:00:00,N,NaT,1.0,NTFY/P&P
290747,L03959,BELL,DEREK,L,NaN,B,M,1978-05-04,2034-05-14 00:00:00,2020-02-27,valid release date,BLACK,MEDIUM,MARTIN C.I.,83.0,2015-08-04,2020-01-17,BROWARD,1700621.0,30323.0,PETIT-THEFT-MISD,17-B P & P,2020-01-17 00:00:00,N,NaT,2.0,NTFY/P&P
314598,M64754,DELEON,CARLOS,NaN,NaN,W,M,1989-01-10,2023-11-06 00:00:00,2021-04-01,valid release date,WHITE,MEDIUM,APALACHEE WEST UNIT,9.0,2019-01-15,2020-10-15,MIAMI-DADE,1901751.0,50000.0,PETIT-THEFT-MISD,MONROE CO SO,2021-04-16 00:00:00,D,NaT,2.0,DETAIN

In [127]:
df_active_theft_PETIT_THEFT_MISD_drop.Race.value_counts()

B    4
W    2
H    1
Name: Race, dtype: int64

In [149]:
df_active_theft_PETIT_THEFT_MISD_drop.Race.value_counts(normalize=True)

B    0.571429
W    0.285714
H    0.142857
Name: Race, dtype: float64

In [ ]:
df_active[df_active.adjudicationcharge_descr.str.contains("CITRUS", case=False, na=False)]

In [145]:
df_active[df_active.adjudicationcharge_descr.str.contains("RETAIL THEFT $300+(2ND CONV.)", case=False, na=False)]

Empty DataFrame
Columns: [DCNumber, LastName, FirstName, MiddleName, NameSuffix, Race, Sex, BirthDate, PrisonReleaseDate, ReceiptDate, releasedateflag_descr, race_descr, custody_description, FACILITY_description, Sequence, OffenseDate, DateAdjudicated, County, CaseNumber, prisonterm, adjudicationcharge_descr, Authority, DetainerDate, DetainerType, RemovalDate, SequenceNo, detainertype_descr]
Index: []

Source: Offender Search Database http://www.dc.state.fl.us/OffenderSearch/InmateInfoMenu.aspx

In [ ]:
df_active_theft[df_active_theft.adjudicationcharge_descr.str.contains("THEFT", case=False, na=False)]
df_active_theft.sample(5)

In [86]:
df_active_theft.head(50)

,DCNumber,LastName,FirstName,MiddleName,NameSuffix,Race,Sex,BirthDate,PrisonReleaseDate,ReceiptDate,releasedateflag_descr,race_descr,custody_description,FACILITY_description,Sequence,OffenseDate,DateAdjudicated,County,CaseNumber,prisonterm,adjudicationcharge_descr,Authority,DetainerDate,DetainerType,RemovalDate,SequenceNo,detainertype_descr
4,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,6.0,2018-04-08,2020-12-21,JACKSON,1800606.0,40000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
6,000119,CARMAN,GARRETT,A,NaN,W,M,1998-06-19,2023-05-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,TALLAHASSEE C.R.C,8.0,2018-04-11,2020-12-21,JACKSON,1800608.0,40000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
39,000166,BATES,BILLIE,S,NaN,W,F,1990-03-26,2023-05-12 00:00:00,2018-11-01,valid release date,WHITE,CLOSE,LOWELL C.I.,2.0,2016-08-28,2018-10-17,INDIAN RIVER,1601219.0,50000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
40,000166,BATES,BILLIE,S,NaN,W,F,1990-03-26,2023-05-12 00:00:00,2018-11-01,valid release date,WHITE,CLOSE,LOWELL C.I.,3.0,2016-08-28,2018-10-17,INDIAN RIVER,1601219.0,50000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
89,000524,BERRY,CANDACE,L,NaN,W,F,1986-03-11,2022-06-20 00:00:00,2021-01-19,valid release date,WHITE,COMMUNITY,SUNCOAST C.R.C.(FEM),2.0,2020-03-01,2020-09-09,COLUMBIA,2000183.0,20900.0,PETIT THEFT/3RD CONVICTION,NaN,NaN,NaN,NaT,NaN,NaN
92,000536,RHODES,JACARIE,NaN,NaN,B,M,2001-01-24,2023-09-10 00:00:00,2021-04-05,valid release date,BLACK,MEDIUM,LAKE CITY C.F.,3.0,2017-12-06,2021-03-22,BROWARD,1804582.0,40000.0,GRAND THEFT MOTOR VEHICLE,17-B P & P,2021-03-22 00:00:00,N,NaT,1.0,NTFY/P&P
95,000536,RHODES,JACARIE,NaN,NaN,B,M,2001-01-24,2023-09-10 00:00:00,2021-04-05,valid release date,BLACK,MEDIUM,LAKE CITY C.F.,6.0,2018-02-07,2021-03-22,BROWARD,1804584.0,40000.0,GRAND THEFT MOTOR VEHICLE,17-B P & P,2021-03-22 00:00:00,N,NaT,1.0,NTFY/P&P
96,000536,RHODES,JACARIE,NaN,NaN,B,M,2001-01-24,2023-09-10 00:00:00,2021-04-05,valid release date,BLACK,MEDIUM,LAKE CITY C.F.,7.0,2019-12-25,2021-03-22,BROWARD,1915052.0,40000.0,GRAND THEFT MOTOR VEHICLE,17-B P & P,2021-03-22 00:00:00,N,NaT,1.0,NTFY/P&P
97,000569,CHRISTMAN,LISA,M,NaN,W,F,1968-02-24,2022-11-13 00:00:00,2021-04-05,valid release date,WHITE,MEDIUM,GADSDEN C.F.,1.0,2020-01-23,2021-02-23,CHARLOTTE,2000299.0,20000.0,GRAND THEFT $750+LT5K,NaN,NaN,NaN,NaT,NaN,NaN
142,004278,THAGGARD,LARRY,B,NaN,W,M,1943-12-10,2033-07-13 00:00:00,1989-01-26,valid release date,WHITE,CLOSE,UNION C.I.,8.0,1988-09-28,1988-12-28,PALM BEACH,8812770.0,30000.0,"GRAND THEFT,$300 LESS &20,000",ST. GEORGIA PO. DEPT,1990-05-14 00:00:00,D,NaT,2.0,DETAIN
143,004278,THAGGARD,LARRY,B,NaN,W,M,1943-12-10,2033-07-13 00:00:00,1989-01-26,valid release date,WHITE,CLOSE,UNION C.I.,8.0,1988-09-28,1988-12-28,PALM BEACH,8812770.0,30000.0,"GRAND THEFT,$300 LESS &20,000",HORRY CO. PD S. CARO,1989-02-02 00:00:00,D,1991-11-21,1.0,DETAIN
172,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,2.0,1989-09-29,1990-05-31,OKALOOSA,8901540.0,100000.0,"GRAND THEFT,$300 LESS &20,000","DOC BATON ROUGH,LA",1984-02-10 00:00:00,D,1994-03-23,1.0,DETAIN
173,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,2.0,1989-09-29,1990-05-31,OKALOOSA,8901540.0,100000.0,"GRAND THEFT,$300 LESS &20,000",ESCAMBIA CO.SO.90-55,1991-04-26 00:00:00,D,1994-03-22,2.0,DETAIN
242,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,37.0,1989-08-05,1991-04-03,ESCAMBIA,9005569.0,100000.0,"GRAND THEFT,$300 LESS &20,000","DOC BATON ROUGH,LA",1984-02-10 00:00:00,D,1994-03-23,1.0,DETAIN
243,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,37.0,1989-08-05,1991-04-03,ESCAMBIA,9005569.0,100000.0,"GRAND THEFT,$300 LESS &20,000",ESCAMBIA CO.SO.90-55,1991-04-26 00:00:00,D,1994-03-22,2.0,DETAIN
250,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,41.0,1989-08-09,1991-04-03,ESCAMBIA,9005572.0,100000.0,"GRAND THEFT,$300 LESS &20,000","DOC BATON ROUGH,LA",1984-02-10 00:00:00,D,1994-03-23,1.0,DETAIN
251,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,41.0,1989-08-09,1991-04-03,ESCAMBIA,9005572.0,100000.0,"GRAND THEFT,$300 LESS &20,000",ESCAMBIA CO.SO.90-55,1991-04-26 00:00:00,D,1994-03-22,2.0,DETAIN
254,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,43.0,1989-08-10,1991-04-03,ESCAMBIA,9005573.0,100000.0,"GRAND THEFT,$300 LESS &20,000","DOC BATON ROUGH,LA",1984-02-10 00:00:00,D,1994-03-23,1.0,DETAIN
255,005355,WRIGHT,EDDIE,NaN,JR.,B,M,1944-11-11,2022-07-29 00:00:00,1991-04-15,valid release date,BLACK,CLOSE,UNION C.I.,43.0,1989-08-10,1991-04-03,ESCAMBIA,9005573.0,100000.0,"GRAND THEFT,$300 LESS &20,000",ESCAMBIA CO.SO.90-55,1991-04-26 00:00:00,D,1994-03-22,2.0,DETAIN
306,008385,WOMMOCK,EUGENE,NaN,NaN,B,M,1945-08-21,NaN,1963-02-28,to be set,BLACK,CLOSE,SANTA ROSA ANNEX,3.0,1967-07-25,1968-02-19,ALACHUA,NaN,50000.0,LARCENY/GRAND THEFT,NaN,NaN,NaN,NaT,NaN,NaN
324,009956,BROWN,GEORGE,NaN,NaN,B,M,1940-11-27,NaN,1967-11-29,life sentence,BLACK,MEDIUM,EVERGLADES C.I.,2.0,1981-11-18,1982-04-13,HILLSBOROUGH,8111194.0,50000.0,"GRAND THEFT,$300 LESS &20,000",POLK CO SO,2002-05-17 00:00:00,D,2002-12-13,1.0,DETAIN
341,010057,SANDERS,AARON,J,NaN,W,M,1984-04-30,2025-07-31 00:00:00,2021-06-07,valid release date,WHITE,CLOSE,FRANKLIN C.I.,37.0,2017-11-26,2021-05-19,HERNANDO,1702793.0,80100.0,THEFT>65YO>$300<$10K,10 YEARS PROBATION,2018-08-15 00:00:00,N,2019-07-01,1.0,NTFY/P&P
355,010071,GALLEGO,RAYNEL,NaN,NaN,W,M,1997-09-06,2022-09-13 00:00:00,2021-08-19,valid release date,WHITE,CLOSE,SOUTH BAY C.F.,4.0,2019-10-10,2021-07-19,MIAMI-DADE,1920172.0,30000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
372,010163,STROUD,KRISHAUNA,NaN,NaN,B,F,1999-11-13,2022-11-18 00:00:00,2019-02-18,valid release date,BLACK,CLOSE,LOWELL ANNEX,1.0,2018-08-05,2019-02-04,OKEECHOBEE,1800529.0,40000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
467,010473,CLEMMONS,JACK,NaN,IV,B,M,1999-03-28,2022-04-05 00:00:00,2021-12-15,valid release date,BLACK,MEDIUM,CFRC-EAST,1.0,2018-06-27,2021-10-20,VOLUSIA,1832822.0,10600.0,GRAND THEFT MOTOR VEHICLE,3CASES 20-32556,2021-10-20 00:00:00,N,NaT,1.0,NTFY/P&P
468,010473,CLEMMONS,JACK,NaN,IV,B,M,1999-03-28,2022-04-05 00:00:00,2021-12-15,valid release date,BLACK,MEDIUM,CFRC-EAST,2.0,2019-01-22,2021-10-20,VOLUSIA,1930461.0,10600.0,GRAND THEFT MOTOR VEHICLE,3CASES 20-32556,2021-10-20 00:00:00,N,NaT,1.0,NTFY/P&P
488,010581,RESTUCHER,JIMMY,A,NaN,W,M,1999-11-05,2024-12-13 00:00:00,2021-04-07,valid release date,WHITE,MEDIUM,LAKE CITY C.F.,2.0,2019-04-27,2021-03-23,ESCAMBIA,1902517.0,50000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
491,010581,RESTUCHER,JIMMY,A,NaN,W,M,1999-11-05,2024-12-13 00:00:00,2021-04-07,valid release date,WHITE,MEDIUM,LAKE CITY C.F.,5.0,2020-02-09,2021-03-23,ESCAMBIA,2000679.0,50000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
494,010586,MASSEY,PAUL,A,NaN,W,M,1946-01-01,NaN,1993-01-15,life sentence,WHITE,CLOSE,AVON PARK C.I.,2.0,1988-02-17,1992-12-18,POLK,8800659.0,40000.0,"GRAND THEFT,$300 LESS &20,000",POLK CO. SO.,1994-10-14 00:00:00,D,2009-05-04,1.0,DETAIN
499,010586,MASSEY,PAUL,A,NaN,W,M,1946-01-01,NaN,1993-01-15,life sentence,WHITE,CLOSE,AVON PARK C.I.,7.0,1993-11-11,1994-08-29,OSCEOLA,9301862.0,9999998.0,"GRAND THEFT,$300 LESS &20,000",POLK CO. SO.,1994-10-14 00:00:00,D,2009-05-04,1.0,DETAIN
519,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,5.0,2018-12-06,2021-04-21,BAY,1903985.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
520,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,6.0,2019-02-12,2021-04-21,BAY,1903986.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
521,010733,PAUL,BRIAN,A,NaN,W,M,1988-02-06,2023-04-30 00:00:00,2021-05-03,valid release date,WHITE,MINIMUM,OKALOOSA C.I.,7.0,2019-03-25,2021-04-21,BAY,1903988.0,30000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
527,010770,WINTHERS,BRYSON,C,NaN,W,M,1995-01-14,2024-05-23 00:00:00,2021-01-25,valid release date,WHITE,MINIMUM,COLUMBIA ANNEX,2.0,2019-02-23,2020-12-04,BAY,1901008.0,40000.0,"GRAND THEFT,300 L/5,000","140BAY 1YR CC,10YR",2020-12-04 00:00:00,N,NaT,1.0,NTFY/P&P
564,011344,JONES,IVAN,D,NaN,B,M,2003-07-08,2030-07-26 00:00:00,2021-12-02,valid release date,BLACK,CLOSE,AVON PARK C.I.,3.0,2020-07-22,2021-09-17,HILLSBOROUGH,2010303.0,50000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
566,011344,JONES,IVAN,D,NaN,B,M,2003-07-08,2030-07-26 00:00:00,2021-12-02,valid release date,BLACK,CLOSE,AVON PARK C.I.,5.0,2020-02-23,2021-09-17,HILLSBOROUGH,2010919.0,50000.0,GRAND THEFT FIREARM,NaN,NaN,NaN,NaT,NaN,NaN
573,011391,MARTIN,WALTER,E,NaN,B,M,1991-08-27,2027-11-29 00:00:00,2022-01-21,valid release date,BLACK,MINIMUM,DADE C.I.,2.0,2019-12-16,2021-11-17,MIAMI-DADE,1923397.0,50000.0,GRAND THEFT MOTOR VEHICLE,8 YRS PRISON/8YRS PR,2022-02-03 00:00:00,N,NaT,1.0,NTFY/P&P
591,011553,TILLMAN,JERRY,NaN,NaN,B,M,1945-11-06,NaN,1975-02-10,life sentence,BLACK,MEDIUM,AVON PARK C.I.,2.0,1985-06-21,1986-04-18,POLK,8503161.0,20000.0,"GRAND THEFT,$300 LESS &20,000",POLK CO S.O.,1986-05-21 00:00:00,D,2020-10-13,1.0,DETAIN
606,012300,STANCLE,RUFUS,NaN,NaN,B,M,1941-05-27,NaN,1964-10-06,life sentence,BLACK,CLOSE,DADE C.I.,3.0,1966-08-29,1967-06-19,COLUMBIA,1446.0,10000.0,GRAND THEFT MOTOR VEHICLE,POLK COUNTY SO,1997-08-08 00:00:00,D,1997-09-02,1.0,DETAIN
617,013109,MILLIGAN,JEROLD,NaN,NaN,W,M,1947-04-19,NaN,1971-08-05,life sentence,WHITE,CLOSE,EVERGLADES C.I.,2.0,1970-11-14,1971-08-03,POLK,7101203.0,50000.0,"GRAND THEFT,$300 LESS &20,000",NaN,NaN,NaN,NaT,NaN,NaN
618,013109,MILLIGAN,JEROLD,NaN,NaN,W,M,1947-04-19,NaN,1971-08-05,life sentence,WHITE,CLOSE,EVERGLADES C.I.,3.0,1971-03-26,1971-08-03,POLK,7106410.0,50000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
741,016450,FLEMING,TIMOTHY,NaN,NaN,B,M,1946-06-21,2027-02-10 00:00:00,2001-10-25,valid release date,BLACK,MINIMUM,SUWANNEE C.I. ANNEX,7.0,2000-07-25,2001-04-20,BROWARD,13134.0,100000.0,"GRAND THEFT,300 L/5,000",NaN,NaN,NaN,NaT,NaN,NaN
765,017584,ROSEMAN,ANDREW,J,NaN,B,M,1944-01-21,2026-06-11 00:00:00,1971-10-27,valid release date,BLACK,CLOSE,DADE C.I.,5.0,1985-06-24,1985-11-08,ORANGE,8503448.0,50000.0,"GRAND THEFT,$300 LESS &20,000",ORANGE CO S/O,1985-12-13 00:00:00,D,1986-07-16,1.0,DETAIN
766,017584,ROSEMAN,ANDREW,J,NaN,B,M,1944-01-21,2026-06-11 00:00:00,1971-10-27,valid release date,BLACK,CLOSE,DADE C.I.,5.0,1985-06-24,1985-11-08,ORANGE,8503448.0,50000.0,"GRAND THEFT,$300 LESS &20,000",NTFY:ORANG.BD.CO.COM,1986-06-11 00:00:00,N,NaT,2.0,NTFY/P&P
767,017584,ROSEMAN,ANDREW,J,NaN,B,M,1944-01-21,2026-06-11 00:00:00,1971-10-27,valid release date,BLACK,CLOSE,DADE C.I.,6.0,1985-06-24,1985-11-08,ORANGE,8503448.0,50000.0,GRAND THEFT MOTOR VEHICLE,ORANGE CO S/O,1985-12-13 00:00:00,D,1986-07-16,1.0,DETAIN
768,017584,ROSEMAN,ANDREW,J,NaN,B,M,1944-01-21,2026-06-11 00:00:00,1971-10-27,valid release date,BLACK,CLOSE,DADE C.I.,6.0,1985-06-24,1985-11-08,ORANGE,8503448.0,50000.0,GRAND THEFT MOTOR VEHICLE,NTFY:ORANG.BD.CO.COM,1986-06-11 00:00:00,N,NaT,2.0,NTFY/P&P
819,019483,RITTER,JACK,NaN,NaN,W,M,1951-02-13,NaN,1992-03-11,life sentence,WHITE,CLOSE,CFRC-MAIN,7.0,1992-01-21,1992-03-02,PASCO,9200230.0,40600.0,"GRAND THEFT,$300 LESS &20,000",HENDRY CO.SO.,1988-02-12 00:00:00,D,1989-09-22,1.0,DETAIN
851,019866,HARRIS,ANTHONY,NaN,JR.,B,M,1949-12-09,NaN,1989-12-22,life sentence,BLACK,CLOSE,DADE C.I.,3.0,1989-03-11,1989-12-15,HILLSBOROUGH,8904088.0,100000.0,GRAND THEFT MOTOR VEHICLE,NaN,NaN,NaN,NaT,NaN,NaN
860,019929,GADSON,JOHN,L,NaN,B,M,1948-01-16,2033-09-13 00:00:00,2002-08-08,valid release date,BLACK,CLOSE,MARTIN C.I.,24.0,2001-02-01,2002-07-17,INDIAN RIVER,100237.0,50000.0,"GRAND THEFT,300 L/5,000",LEE CO. SO.,1992-09-14 00:00:00,D,1993-11-10,2.0,DETAIN
861,019929,GADSON,JOHN,L,NaN,B,M,1948-01-16,2033-09-13 00:00:00,2002-08-08,valid release date,BLACK,CLOSE,MARTIN C.I.,24.0,2001-02-01,2002-07-17,INDIAN RIVER,100237.0,50000.0,"GRAND THEFT,300 L/5,000",PALM BEACH CO SO,2009-10-14 00:00:00,D,NaT,3.0,DETAIN

In [71]:
df_active.adjudicationcharge_descr.str.contains('THEFT', case=False, na=False)

0         False
1         False
2         False
3         False
4          True
          ...
474768    False
474769    False
474770    False
474771    False
474772    False
Name: adjudicationcharge_descr, Length: 474773, dtype: object

In [72]:
df_release.adjudicationcharge_descr.str.contains('THEFT', case=False)

0          NaN
1          NaN
2          NaN
3          NaN
4          NaN
          ...
3980141    NaN
3980142    NaN
3980143    NaN
3980144    NaN
3980145    NaN
Name: adjudicationcharge_descr, Length: 3980146, dtype: object